spring.application.name=fraud-detection
spring.datasource.url=jdbc:postgresql://localhost:5432/frauddb
spring.datasource.username=postgres
spring.datasource.password=Chaitu0814

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ? AI Fraud Detection API
ai.fraud.api.url=http://127.0.0.1:5000/predict

# ? EMAIL CONFIG

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=chaitanyamhatre0805c@gmail.com

spring.mail.password=uhhdzjujuvsczsez

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.starttls.required=true